### PR TITLE
Presentation, movies and source code for my SimpleCV / PyShot project

### PR DESCRIPTION
**Pull request by mjmoorhouse**
My stuff as presented yesterday - a few changes, described in the presentation document (LibreOffice native format).  Also the videos & source code.

### CODE REVIEW

**Comment by cltrudeau** [comment]
Hi Mike,

Any reason you closed this off?  Changed your mind?  If you still want to share, my only request is to put all this stuff in its own directory: 2016/04/PyShot/ would be good.

**Comment by mjmoorhouse** [comment]
Nope- reason is likely incompetence ( did a couple of attempts, put stuff
in the wrong place) same material is in my GitHib Repo.
I'm shooting today, sort it out tonight if you haven't grabbed it from
mjmoorhouse/PyShot Repo in the meantime.
Sorry about this.

**Comment by cltrudeau** [comment]
Since you've already got a repo, how about we just link to it, instead of
duplicating the code?
...ct

**Comment by mjmoorhouse** [comment]
Christopher,
Sure - can do.  I won't be removing my version of information in the Repo
in the near future.
Michael M.

**Pull request closed without merging**
